function temp = getTempCategory(biome)
    T = {'OCEAN', 'MEDIUM', 'WARM', 'MEDIUM', 'MEDIUM', 'MEDIUM', 'MEDIUM', 'MEDIUM',...
        'MEDIUM', 'MEDIUM', 'OCEAN', 'MEDIUM', 'COLD', 'MEDIUM', 'MEDIUM', 'MEDIUM',...
        'MEDIUM', 'MEDIUM', 'MEDIUM', 'MEDIUM', 'MEDIUM', 'MEDIUM', 'MEDIUM', 'MEDIUM',...
        'OCEAN', 'MEDIUM', 'MEDIUM', 'MEDIUM', 'MEDIUM', 'MEDIUM', 'COLD', 'MEDIUM',...
        'MEDIUM', 'MEDIUM', 'MEDIUM', 'WARM', 'MEDIUM', 'MEDIUM', 'WARM', 'WARM'};
    temp = T{biome + 1};
end